name: Build example
on:
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v5
     - name: setup Node
       uses: actions/setup-node@v4
       with: 
         node-version: "20.x"
     - name: install dependencies
       run: npm install
     - name: Install dependencies
       run: npm install
     - name: Run tests with coverage
       run: |
         npm test -- \
            --reporters=default \
            --reporters=jest-junit
          # Coverage typically outputs coverage/clover.xml
     - name: Bundle code into ZIP
       run: |
        mkdir build
        zip -r build/app.zip . -x "build/*"
     - name: Better Test Reports Action
      # You may pin to the exact commit or the version.
      # uses: mridang/action-test-reporter@720c9c56f73e527681bcb30c33da4ccd62bf70fb
       uses: mridang/action-test-reporter@v1.3.0
       with: # GitHub token used to authenticate API requests. Required for checking status checks and publishing releases. Use `secrets.GITHUB_TOKEN` or a PAT with elevated scopes if needed.
         github-token: calculator-app-finished/.github/workflows/ # The directory where your project is located, used as the base for making file paths in the report relative.

         working-directory: . # optional, default is . # The path to the single code coverage report file you want to parse (e.g., 'build/reports/clover.xml').

         coverage-file: coverage/clover.xml  # Set to `true` to upload the generated coverage report as a workflow artifact. If omitted or left empty, this defaults to `true`. Set to `false` to disable artifact upload.

         upload-coverage-report: true # optional, default is true
          
