name: Build example
on:
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v5
     - name: setup Node
       uses: actions/setup-node@v4
       with: 
         node-version: "20.x"
     - name: install dependencies
       run: npm install
     - name: Bundle code into ZIP
       run: |
        mkdir build
        zip -r build/app.zip . -x "build/*"
