name: Dependencies example
on:
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v5
     - name: setup Node
       uses: actions/setup-node@v4
     - name: verification
       run: ls -alhR
